wget https://storage.googleapis.com/syzkaller/corpus/ci-qemu-gce-upstream-auto-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-qemu-native-arm64-kvm-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-qemu-upstream-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-qemu-upstream-386-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-qemu2-arm32-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-qemu2-arm64-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-qemu2-arm64-compat-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-qemu2-arm64-mte-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-qemu2-riscv64-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-snapshot-upstream-root-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-upstream-bpf-kasan-gce-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-upstream-bpf-next-kasan-gce-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-upstream-gce-arm64-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-upstream-gce-leak-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-upstream-kasan-badwrites-root-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-upstream-kasan-gce-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-upstream-kasan-gce-386-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-upstream-kasan-gce-root-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-upstream-kasan-gce-selinux-root-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-upstream-kasan-gce-smack-root-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-upstream-kmsan-gce-386-root-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-upstream-kmsan-gce-root-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-upstream-linux-next-kasan-gce-root-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-upstream-net-kasan-gce-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-upstream-net-this-kasan-gce-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci-upstream-rust-kasan-gce-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci2-upstream-fs-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci2-upstream-kcsan-gce-corpus.db
wget https://storage.googleapis.com/syzkaller/corpus/ci2-upstream-usb-corpus.db
